/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/auth/google/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Start Google Auth
         * @description Redirects the user to Google for authentication.
         */
        get: operations["start_google_auth_v1_auth_google_start_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Google Auth Callback
         * @description Handles the callback from Google and issues JWT tokens.
         */
        get: operations["google_auth_callback_v1_auth_google_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Token
         * @description Refreshes the access token using a valid refresh token.
         */
        post: operations["refresh_token_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Logs the user out by clearing cookies and invalidating the refresh token.
         */
        post: operations["logout_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current User
         * @description Returns the current authenticated user's info.
         */
        get: operations["get_current_user_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/trips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Trips
         * @description List trips for the current user with latest snapshot prices.
         */
        get: operations["list_trips_v1_trips_get"];
        put?: never;
        /**
         * Create Trip
         * @description Create a new trip for the current user.
         */
        post: operations["create_trip_v1_trips_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/trips/refresh-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh All Trips
         * @description Trigger a manual refresh for all active trips.
         */
        post: operations["refresh_all_trips_v1_trips_refresh_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/trips/refresh-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Refresh Status
         * @description Check refresh workflow progress.
         */
        get: operations["refresh_status_v1_trips_refresh_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/trips/{trip_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Trip Details
         * @description Get trip details including prefs, notification rules, and price history.
         */
        get: operations["get_trip_details_v1_trips__trip_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Trip
         * @description Delete a trip and all associated records.
         */
        delete: operations["delete_trip_v1_trips__trip_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/trips/{trip_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Trip Status
         * @description Pause or resume trip tracking.
         */
        patch: operations["update_trip_status_v1_trips__trip_id__status_patch"];
        trace?: never;
    };
    "/v1/locations/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Locations
         * @description Search airports and cities by keyword.
         */
        get: operations["search_locations_v1_locations_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** APIResponse[RefreshStartResponse] */
        APIResponse_RefreshStartResponse_: {
            data: components["schemas"]["RefreshStartResponse"];
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
        };
        /** APIResponse[RefreshStatusResponse] */
        APIResponse_RefreshStatusResponse_: {
            data: components["schemas"]["RefreshStatusResponse"];
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
        };
        /** APIResponse[TripDetailResponse] */
        APIResponse_TripDetailResponse_: {
            data: components["schemas"]["TripDetailResponse"];
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
        };
        /** APIResponse[TripDetail] */
        APIResponse_TripDetail_: {
            data: components["schemas"]["TripDetail"];
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
        };
        /** APIResponse[TripResponse] */
        APIResponse_TripResponse_: {
            data: components["schemas"]["TripResponse"];
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
        };
        /** APIResponse[list[LocationResult]] */
        APIResponse_list_LocationResult__: {
            /** Data */
            data: components["schemas"]["LocationResult"][];
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
        };
        /** APIResponse[list[TripResponse]] */
        APIResponse_list_TripResponse__: {
            /** Data */
            data: components["schemas"]["TripResponse"][];
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * CabinClass
         * @description Flight cabin class options.
         * @enum {string}
         */
        CabinClass: "economy" | "premium_economy" | "business" | "first";
        /**
         * FlightOffer
         * @description Schema for a flight offer.
         */
        FlightOffer: {
            /** Id */
            id: string;
            /** Airline Code */
            airline_code?: string | null;
            /** Airline Name */
            airline_name?: string | null;
            /** Price */
            price: string;
            /** Departure Time */
            departure_time?: string | null;
            /** Arrival Time */
            arrival_time?: string | null;
            /** Duration Minutes */
            duration_minutes?: number | null;
            /**
             * Stops
             * @default 0
             */
            stops: number;
            /** Return Flight */
            return_flight?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * FlightPrefs
         * @description Flight preferences for a trip.
         */
        FlightPrefs: {
            /**
             * Airlines
             * @description Preferred airline IATA codes (e.g., ['UA', 'NH'])
             */
            airlines?: string[];
            /**
             * @description Flight stops preference
             * @default any
             */
            stops_mode: components["schemas"]["StopsMode"];
            /**
             * Max Stops
             * @description Maximum number of stops (only used when stops_mode is 'any')
             */
            max_stops?: number | null;
            /**
             * @description Preferred cabin class
             * @default economy
             */
            cabin: components["schemas"]["CabinClass"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HotelOffer
         * @description Schema for a hotel offer.
         */
        HotelOffer: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Price */
            price: string;
            /** Rating */
            rating?: number | null;
            /** Address */
            address?: string | null;
            /** Description */
            description?: string | null;
        };
        /**
         * HotelPrefs
         * @description Hotel preferences for a trip.
         */
        HotelPrefs: {
            /**
             * Rooms
             * @description Number of rooms needed
             * @default 1
             */
            rooms: number;
            /**
             * Adults Per Room
             * @description Number of adults per room
             * @default 2
             */
            adults_per_room: number;
            /**
             * @description How to select rooms: cheapest or preferred
             * @default cheapest
             */
            room_selection_mode: components["schemas"]["RoomSelectionMode"];
            /**
             * Preferred Room Types
             * @description Preferred room types (e.g., ['King', 'Suite'])
             */
            preferred_room_types?: string[];
            /**
             * Preferred Views
             * @description Preferred views (e.g., ['Ocean', 'City'])
             */
            preferred_views?: string[];
        };
        /**
         * LocationResult
         * @description Airport or city location result.
         */
        LocationResult: {
            /**
             * Code
             * @description IATA location code
             */
            code: string;
            /**
             * Name
             * @description Location name
             */
            name: string;
            /**
             * Type
             * @description Location type (AIRPORT or CITY)
             */
            type: string;
        };
        /**
         * NotificationPrefs
         * @description Notification preferences for a trip.
         */
        "NotificationPrefs-Input": {
            /**
             * @description What price to compare against threshold
             * @default trip_total
             */
            threshold_type: components["schemas"]["ThresholdType"];
            /**
             * Threshold Value
             * @description Price threshold for notifications
             */
            threshold_value: number | string;
            /**
             * Notify Without Threshold
             * @description Send notification on every refresh regardless of threshold
             * @default false
             */
            notify_without_threshold: boolean;
            /**
             * Email Enabled
             * @description Enable email notifications
             * @default true
             */
            email_enabled: boolean;
            /**
             * Sms Enabled
             * @description Enable SMS notifications
             * @default false
             */
            sms_enabled: boolean;
        };
        /**
         * NotificationPrefs
         * @description Notification preferences for a trip.
         */
        "NotificationPrefs-Output": {
            /**
             * @description What price to compare against threshold
             * @default trip_total
             */
            threshold_type: components["schemas"]["ThresholdType"];
            /**
             * Threshold Value
             * @description Price threshold for notifications
             */
            threshold_value: string;
            /**
             * Notify Without Threshold
             * @description Send notification on every refresh regardless of threshold
             * @default false
             */
            notify_without_threshold: boolean;
            /**
             * Email Enabled
             * @description Enable email notifications
             * @default true
             */
            email_enabled: boolean;
            /**
             * Sms Enabled
             * @description Enable SMS notifications
             * @default false
             */
            sms_enabled: boolean;
        };
        /**
         * PriceSnapshotResponse
         * @description Schema for price snapshot in trip history.
         */
        PriceSnapshotResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Flight Price */
            flight_price?: string | null;
            /** Hotel Price */
            hotel_price?: string | null;
            /** Total Price */
            total_price?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Flight Offers */
            flight_offers?: components["schemas"]["FlightOffer"][];
            /** Hotel Offers */
            hotel_offers?: components["schemas"]["HotelOffer"][];
        };
        /**
         * RefreshStartResponse
         * @description Schema for refresh start response.
         */
        RefreshStartResponse: {
            /** Refresh Group Id */
            refresh_group_id: string;
        };
        /**
         * RefreshStatusResponse
         * @description Schema for refresh status response.
         */
        RefreshStatusResponse: {
            /** Refresh Group Id */
            refresh_group_id: string;
            /** Status */
            status: string;
            /** Total */
            total: number;
            /** Completed */
            completed: number;
            /** Failed */
            failed: number;
            /** In Progress */
            in_progress: number;
        };
        /**
         * RoomSelectionMode
         * @description Hotel room selection preference modes.
         * @enum {string}
         */
        RoomSelectionMode: "cheapest" | "preferred";
        /**
         * StopsMode
         * @description Flight stops preference modes.
         * @enum {string}
         */
        StopsMode: "nonstop" | "1-stop" | "any";
        /**
         * ThresholdType
         * @description Notification threshold types for price alerts.
         * @enum {string}
         */
        ThresholdType: "trip_total" | "flight_total" | "hotel_total";
        /**
         * TripCreate
         * @description Schema for creating a new trip.
         */
        TripCreate: {
            /**
             * Name
             * @description Trip name (must be unique per user)
             */
            name: string;
            /**
             * Origin Airport
             * @description Origin airport IATA code (e.g., 'SFO')
             */
            origin_airport: string;
            /**
             * Destination Code
             * @description Destination airport IATA code (e.g., 'MCO')
             */
            destination_code: string;
            /**
             * Is Round Trip
             * @description Whether this is a round trip
             * @default true
             */
            is_round_trip: boolean;
            /**
             * Depart Date
             * Format: date
             * @description Departure date
             */
            depart_date: string;
            /**
             * Return Date
             * Format: date
             * @description Return date
             */
            return_date: string;
            /**
             * Adults
             * @description Number of adult travelers
             * @default 1
             */
            adults: number;
            /** @description Flight preferences (optional) */
            flight_prefs?: components["schemas"]["FlightPrefs"] | null;
            /** @description Hotel preferences (optional) */
            hotel_prefs?: components["schemas"]["HotelPrefs"] | null;
            /** @description Notification settings (required) */
            notification_prefs: components["schemas"]["NotificationPrefs-Input"];
        };
        /**
         * TripDetail
         * @description Schema for detailed trip response with all preferences.
         */
        TripDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Origin Airport */
            origin_airport: string;
            /** Destination Code */
            destination_code: string;
            /**
             * Depart Date
             * Format: date
             */
            depart_date: string;
            /**
             * Return Date
             * Format: date
             */
            return_date: string;
            status: components["schemas"]["TripStatus"];
            /** Current Flight Price */
            current_flight_price?: string | null;
            /** Current Hotel Price */
            current_hotel_price?: string | null;
            /** Total Price */
            total_price?: string | null;
            /** Last Refreshed */
            last_refreshed?: string | null;
            /** Is Round Trip */
            is_round_trip: boolean;
            /** Adults */
            adults: number;
            flight_prefs?: components["schemas"]["FlightPrefs"] | null;
            hotel_prefs?: components["schemas"]["HotelPrefs"] | null;
            notification_prefs?: components["schemas"]["NotificationPrefs-Output"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * TripDetailResponse
         * @description Schema for trip detail response with price history.
         */
        TripDetailResponse: {
            trip: components["schemas"]["TripDetail"];
            /** Price History */
            price_history: components["schemas"]["PriceSnapshotResponse"][];
        };
        /**
         * TripResponse
         * @description Schema for trip list response.
         */
        TripResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Origin Airport */
            origin_airport: string;
            /** Destination Code */
            destination_code: string;
            /**
             * Depart Date
             * Format: date
             */
            depart_date: string;
            /**
             * Return Date
             * Format: date
             */
            return_date: string;
            status: components["schemas"]["TripStatus"];
            /** Current Flight Price */
            current_flight_price?: string | null;
            /** Current Hotel Price */
            current_hotel_price?: string | null;
            /** Total Price */
            total_price?: string | null;
            /** Last Refreshed */
            last_refreshed?: string | null;
        };
        /**
         * TripStatus
         * @description Trip tracking status values.
         * @enum {string}
         */
        TripStatus: "active" | "paused" | "error";
        /**
         * TripStatusUpdate
         * @description Schema for updating trip status (pause/resume).
         */
        TripStatusUpdate: {
            /**
             * Status
             * @description New status: 'active' or 'paused'
             * @enum {string}
             */
            status: "active" | "paused";
        };
        /**
         * UserResponse
         * @description Response model for authenticated user info.
         */
        UserResponse: {
            /** Id */
            id: string;
            /** Email */
            email: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    start_google_auth_v1_auth_google_start_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    google_auth_callback_v1_auth_google_callback_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    refresh_token_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    logout_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_current_user_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    list_trips_v1_trips_get: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                status?: components["schemas"]["TripStatus"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_list_TripResponse__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_trip_v1_trips_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_TripDetail_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_all_trips_v1_trips_refresh_all_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_RefreshStartResponse_"];
                };
            };
        };
    };
    refresh_status_v1_trips_refresh_status_get: {
        parameters: {
            query: {
                refresh_group_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_RefreshStatusResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trip_details_v1_trips__trip_id__get: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
            };
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_TripDetailResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_trip_v1_trips__trip_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_trip_status_v1_trips__trip_id__status_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripStatusUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_TripResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_locations_v1_locations_search_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_list_LocationResult__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
