/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/auth/google/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Start Google Auth
         * @description Redirects the user to Google for authentication.
         */
        get: operations["start_google_auth_v1_auth_google_start_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Google Auth Callback
         * @description Handles the callback from Google and issues JWT tokens.
         */
        get: operations["google_auth_callback_v1_auth_google_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/mobile-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mobile Token
         * @description Exchange a Google ID token (from the native app) for the same JWT pair the
         *     web OAuth callback issues. Returns the pair in the body — the mobile client
         *     stores it in expo-secure-store and sends `Authorization: Bearer`.
         */
        post: operations["mobile_token_v1_auth_mobile_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Token
         * @description Refresh the access token. Web sends the refresh token in the
         *     ``refresh_token_cookie`` cookie and gets new cookies back; mobile sends it in
         *     a JSON body (``{"refresh_token": ...}``) and gets the new pair in the body.
         */
        post: operations["refresh_token_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Logs the user out by clearing cookies and invalidating the refresh token.
         */
        post: operations["logout_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/test-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test Login
         * @description Test-only login. Creates a test user, wipes their existing trips, and
         *     sets JWT cookies. Only available when ENVIRONMENT=test.
         *
         *     The trip wipe keeps E2E runs idempotent — without it, the per-user
         *     `MAX_TRIPS_PER_USER` cap (10) is hit after a few runs of any test that
         *     creates a trip, and subsequent POST /v1/trips calls fail with 400
         *     `TripLimitExceeded` even though the request itself is valid.
         */
        post: operations["test_login_v1_auth_test_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/e2e/mint-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * E2E Mint Token
         * @description Mint a bearer JWT pair for the synthetic e2e user (P4 mobile-e2e harness).
         *
         *     Doubly gated: inert (404) unless `E2E_MODE` is on, and requires the shared
         *     `X-E2E-Token` secret. Returns the pair in the body; the access_token then
         *     authenticates via the Bearer path in get_current_user (Task 1). Only ever
         *     enabled on the isolated vpt-e2e backend, never normal prod.
         */
        post: operations["e2e_mint_token_v1_e2e_mint_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current User
         * @description Returns the current authenticated user's info.
         */
        get: operations["get_current_user_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/trips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Trips
         * @description List trips for the current user with latest snapshot prices.
         */
        get: operations["list_trips_v1_trips_get"];
        put?: never;
        /**
         * Create Trip
         * @description Create a new trip for the current user.
         */
        post: operations["create_trip_v1_trips_post"];
        /**
         * Delete All Trips
         * @description Delete all trips for the current user.
         */
        delete: operations["delete_all_trips_v1_trips_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/trips/{trip_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Trip Details
         * @description Get trip details including prefs, notification rules, and price history.
         */
        get: operations["get_trip_details_v1_trips__trip_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Trip
         * @description Delete a trip and all associated records.
         */
        delete: operations["delete_trip_v1_trips__trip_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Trip
         * @description Update an existing trip's details, preferences, and notifications.
         */
        patch: operations["update_trip_v1_trips__trip_id__patch"];
        trace?: never;
    };
    "/v1/trips/refresh-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh All Trips
         * @description Trigger a manual refresh for all active trips.
         */
        post: operations["refresh_all_trips_v1_trips_refresh_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/trips/refresh-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Refresh Status
         * @description Check refresh workflow progress.
         */
        get: operations["refresh_status_v1_trips_refresh_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/trips/{trip_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Trip Status
         * @description Pause or resume trip tracking.
         */
        patch: operations["update_trip_status_v1_trips__trip_id__status_patch"];
        trace?: never;
    };
    "/v1/trips/{trip_id}/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Trip
         * @description Trigger a manual price refresh for a single trip.
         */
        post: operations["refresh_trip_v1_trips__trip_id__refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send Message
         * @description Send a chat message and stream the response.
         *
         *     This endpoint accepts a user message and returns a Server-Sent Events (SSE)
         *     stream with the assistant's response. The stream includes:
         *
         *     - **content**: Text content from the LLM
         *     - **tool_call**: When the LLM invokes a tool
         *     - **tool_result**: Result from tool execution
         *     - **error**: If an error occurs
         *     - **done**: Stream completion marker
         *
         *     Each chunk is a JSON object with a `type` field indicating the chunk type.
         *
         *     Args:
         *         request: Chat message request body.
         *         db: Database session.
         *         current_user: Authenticated user.
         *         svc: Chat service instance.
         *
         *     Returns:
         *         StreamingResponse with SSE content.
         */
        post: operations["send_message_v1_chat_messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Conversations
         * @description List the current user's conversations.
         *
         *     Returns conversations sorted by most recently updated.
         *
         *     Args:
         *         limit: Maximum number of conversations to return.
         *         offset: Number of conversations to skip.
         *         db: Database session.
         *         current_user: Authenticated user.
         *         svc: Conversation service instance.
         *
         *     Returns:
         *         List of conversation metadata.
         */
        get: operations["list_conversations_v1_chat_conversations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat/conversations/{thread_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Conversation
         * @description Get a conversation with its message history.
         *
         *     Args:
         *         thread_id: Conversation UUID.
         *         limit: Maximum number of messages to return.
         *         db: Database session.
         *         current_user: Authenticated user.
         *         svc: Chat service instance.
         *
         *     Returns:
         *         Conversation metadata and messages.
         *
         *     Raises:
         *         ConversationNotFound: If conversation doesn't exist or doesn't belong to user.
         */
        get: operations["get_conversation_v1_chat_conversations__thread_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Conversation
         * @description Delete a conversation and all its messages.
         *
         *     Args:
         *         thread_id: Conversation UUID to delete.
         *         db: Database session.
         *         current_user: Authenticated user.
         *         svc: Conversation service instance.
         *
         *     Raises:
         *         ConversationNotFound: If conversation doesn't exist or doesn't belong to user.
         */
        delete: operations["delete_conversation_v1_chat_conversations__thread_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat/elicitation/{tool_call_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Elicitation
         * @description Submit elicitation form data to complete a pending tool execution.
         *
         *     When a tool requests elicitation (missing required fields), the frontend
         *     displays a form to collect the data. This endpoint receives the submitted
         *     form data and executes the tool with complete arguments.
         *
         *     The response is an SSE stream containing:
         *     - **tool_result**: Result from the tool execution
         *     - **content**: Follow-up text from the LLM
         *     - **tool_call**: Any additional tool calls (e.g., trigger_refresh)
         *     - **done**: Stream completion marker
         *
         *     Args:
         *         tool_call_id: Unique identifier from the elicitation request.
         *         request: Elicitation submission containing thread_id, tool_name, and form data.
         *         db: Database session.
         *         current_user: Authenticated user.
         *         conv_svc: Conversation service instance.
         *         svc: Chat service instance.
         *
         *     Returns:
         *         StreamingResponse with SSE content.
         *
         *     Raises:
         *         ConversationNotFound: If the conversation doesn't exist or doesn't belong to user.
         *         ToolNotRegistered: If the specified tool is not registered.
         */
        post: operations["submit_elicitation_v1_chat_elicitation__tool_call_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sse/updates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Price Updates
         * @description Stream real-time price updates via Server-Sent Events.
         *
         *     This endpoint provides a persistent connection that streams price updates
         *     for all of the authenticated user's trips.
         *
         *     Events:
         *     - `connected`: Sent immediately upon connection.
         *     - `price_update`: Sent when a trip's price snapshot is updated.
         *     - `heartbeat`: Sent periodically to keep the connection alive.
         *     - `error`: Sent when an error occurs.
         *
         *     Query Parameters:
         *     - `heartbeat_interval`: Seconds between heartbeats (default: 30, range: 5-60).
         *     - `poll_interval`: Seconds between database polls (default: 5, range: 1-30).
         */
        get: operations["stream_price_updates_v1_sse_updates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sse/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Sse Status
         * @description Check SSE endpoint availability.
         *
         *     Returns status information for debugging SSE connections.
         */
        get: operations["get_sse_status_v1_sse_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/notifications/device-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register Device Token
         * @description Register (or upsert) the caller's Expo push token for this device.
         */
        post: operations["register_device_token_v1_notifications_device_token_post"];
        /**
         * Unregister Device Token
         * @description Unregister a device token on sign-out. Idempotent (no-op if absent).
         */
        delete: operations["unregister_device_token_v1_notifications_device_token_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/feature-flags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Feature Flags
         * @description List every known feature flag with its live state (admin users only).
         */
        get: operations["get_feature_flags_v1_feature_flags_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/feature-flags/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Feature Flag
         * @description Set a known feature flag's enabled state (admin users only).
         *
         *     PATCH (not PUT) so the browser call passes the API's deliberately pinned
         *     CORS method allowlist (GET/POST/PATCH/DELETE — see app.main).
         */
        patch: operations["update_feature_flag_v1_feature_flags__name__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** APIResponse[BulkDeleteResponse] */
        APIResponse_BulkDeleteResponse_: {
            data: components["schemas"]["BulkDeleteResponse"];
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
        };
        /** APIResponse[ChatResponse] */
        APIResponse_ChatResponse_: {
            data: components["schemas"]["ChatResponse"];
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
        };
        /** APIResponse[RefreshStartResponse] */
        APIResponse_RefreshStartResponse_: {
            data: components["schemas"]["RefreshStartResponse"];
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
        };
        /** APIResponse[RefreshStatusResponse] */
        APIResponse_RefreshStatusResponse_: {
            data: components["schemas"]["RefreshStatusResponse"];
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
        };
        /** APIResponse[TripDetailResponse] */
        APIResponse_TripDetailResponse_: {
            data: components["schemas"]["TripDetailResponse"];
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
        };
        /** APIResponse[TripDetail] */
        APIResponse_TripDetail_: {
            data: components["schemas"]["TripDetail"];
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
        };
        /** APIResponse[TripResponse] */
        APIResponse_TripResponse_: {
            data: components["schemas"]["TripResponse"];
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
        };
        /** APIResponse[list[ConversationResponse]] */
        APIResponse_list_ConversationResponse__: {
            /** Data */
            data: components["schemas"]["ConversationResponse"][];
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
        };
        /** APIResponse[list[TripResponse]] */
        APIResponse_list_TripResponse__: {
            /** Data */
            data: components["schemas"]["TripResponse"][];
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * BulkDeleteResponse
         * @description Schema for bulk delete response.
         */
        BulkDeleteResponse: {
            /** Deleted Count */
            deleted_count: number;
        };
        /**
         * CabinClass
         * @description Flight cabin class options.
         * @enum {string}
         */
        CabinClass: "economy" | "premium_economy" | "business" | "first";
        /**
         * ChatMessageResponse
         * @description Response model for a single chat message in history.
         */
        ChatMessageResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Role */
            role: string;
            /** Content */
            content: string;
            /** Tool Calls */
            tool_calls?: {
                [key: string]: unknown;
            }[] | null;
            /** Tool Call Id */
            tool_call_id?: string | null;
            /** Name */
            name?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * ChatRequest
         * @description Request body for sending a chat message.
         *
         *     Attributes:
         *         message: The user's message content.
         *         thread_id: Optional conversation thread ID. If not provided,
         *                   a new conversation will be created.
         */
        ChatRequest: {
            /**
             * Message
             * @description The user's message content
             */
            message: string;
            /**
             * Thread Id
             * @description Conversation thread ID. If not provided, creates a new conversation.
             */
            thread_id?: string | null;
        };
        /**
         * ChatResponse
         * @description Response model for non-streaming chat operations.
         *
         *     Used for conversation listing and retrieval, not for the
         *     main streaming chat endpoint.
         */
        ChatResponse: {
            conversation: components["schemas"]["ConversationResponse"];
            /** Messages */
            messages?: components["schemas"]["ChatMessageResponse"][];
        };
        /**
         * ConversationResponse
         * @description Response model for conversation metadata.
         */
        ConversationResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * DeviceTokenRegister
         * @description Register/unregister payload: the Expo push token + originating platform.
         */
        DeviceTokenRegister: {
            /** Expo Push Token */
            expo_push_token: string;
            /** Platform */
            platform: string;
        };
        /**
         * DeviceTokenResponse
         * @description The registered token (echoed back to confirm the upsert).
         */
        DeviceTokenResponse: {
            /** Expo Push Token */
            expo_push_token: string;
            /** Platform */
            platform: string;
        };
        /**
         * ElicitationSubmissionRequest
         * @description Request body for submitting elicitation form data.
         *
         *     Used with POST /v1/chat/elicitation/{tool_call_id} to submit
         *     user-provided form data and complete a pending tool execution.
         *
         *     Attributes:
         *         thread_id: The conversation thread ID where elicitation occurred.
         *         tool_name: Name of the tool being executed (for validation).
         *         data: The form data submitted by the user.
         */
        ElicitationSubmissionRequest: {
            /**
             * Thread Id
             * Format: uuid
             * @description Conversation thread ID where the elicitation was requested.
             */
            thread_id: string;
            /**
             * Tool Name
             * @description Name of the tool that requested elicitation.
             */
            tool_name: string;
            /**
             * Data
             * @description Form data submitted by the user to complete the tool call.
             */
            data: {
                [key: string]: unknown;
            };
        };
        /** FeatureFlagItem */
        FeatureFlagItem: {
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Enabled */
            enabled: boolean;
        };
        /** FeatureFlagUpdate */
        FeatureFlagUpdate: {
            /** Enabled */
            enabled: boolean;
        };
        /** FeatureFlagsResponse */
        FeatureFlagsResponse: {
            /** Flags */
            flags: components["schemas"]["FeatureFlagItem"][];
        };
        /**
         * FlightItinerary
         * @description Complete itinerary (outbound or return) with all segments.
         */
        FlightItinerary: {
            /** Direction */
            direction: string;
            /** Segments */
            segments?: components["schemas"]["FlightSegment"][];
            /** Total Duration Minutes */
            total_duration_minutes?: number | null;
            /**
             * Stops
             * @default 0
             */
            stops: number;
        };
        /**
         * FlightOffer
         * @description Schema for a flight offer.
         */
        FlightOffer: {
            /** Id */
            id: string;
            /** Airline Code */
            airline_code?: string | null;
            /** Flight Number */
            flight_number?: string | null;
            /** Airline Name */
            airline_name?: string | null;
            /** Price */
            price: string;
            /** Departure Time */
            departure_time?: string | null;
            /** Arrival Time */
            arrival_time?: string | null;
            /** Duration Minutes */
            duration_minutes?: number | null;
            /**
             * Stops
             * @default 0
             */
            stops: number;
            /** Return Flight */
            return_flight?: {
                [key: string]: unknown;
            } | null;
            /** Itineraries */
            itineraries?: components["schemas"]["FlightItinerary"][];
        };
        /**
         * FlightPrefs
         * @description Flight preferences for a trip.
         */
        FlightPrefs: {
            /**
             * Airlines
             * @description Preferred airline IATA codes (e.g., ['UA', 'NH'])
             */
            airlines?: string[];
            /**
             * @description Flight stops preference
             * @default any
             */
            stops_mode: components["schemas"]["StopsMode"];
            /**
             * Max Stops
             * @description Maximum number of stops (only used when stops_mode is 'any')
             */
            max_stops?: number | null;
            /**
             * @description Preferred cabin class
             * @default economy
             */
            cabin: components["schemas"]["CabinClass"];
        };
        /**
         * FlightSegment
         * @description A single flight segment.
         */
        FlightSegment: {
            /** Carrier Code */
            carrier_code?: string | null;
            /** Flight Number */
            flight_number?: string | null;
            /** Departure Airport */
            departure_airport?: string | null;
            /** Arrival Airport */
            arrival_airport?: string | null;
            /** Departure Time */
            departure_time?: string | null;
            /** Arrival Time */
            arrival_time?: string | null;
            /** Duration Minutes */
            duration_minutes?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HotelOffer
         * @description Schema for a hotel offer.
         */
        HotelOffer: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Price */
            price: string;
            /** Rating */
            rating?: number | null;
            /** Address */
            address?: string | null;
            /** Description */
            description?: string | null;
        };
        /**
         * HotelPrefs
         * @description Hotel preferences for a trip.
         */
        HotelPrefs: {
            /**
             * Rooms
             * @description Number of rooms needed
             * @default 1
             */
            rooms: number;
            /**
             * Adults Per Room
             * @description Number of adults per room
             * @default 2
             */
            adults_per_room: number;
            /**
             * City
             * @description Free-text city name sent to the Skiplagged hotel search (overrides destination airport)
             */
            city?: string | null;
            /**
             * @description How to select rooms: cheapest or preferred
             * @default cheapest
             */
            room_selection_mode: components["schemas"]["RoomSelectionMode"];
            /**
             * Preferred Room Types
             * @description Preferred room types (e.g., ['King', 'Suite'])
             */
            preferred_room_types?: string[];
            /**
             * Preferred Views
             * @description Preferred views (e.g., ['Ocean', 'City'])
             */
            preferred_views?: string[];
            /**
             * Min Star Rating
             * @description Minimum hotel star rating (1-5). Hotels below this rating are filtered out.
             */
            min_star_rating?: number | null;
        };
        /**
         * MobileTokenRequest
         * @description Body the native app POSTs: a Google ID token obtained via Expo AuthSession.
         */
        MobileTokenRequest: {
            /** Id Token */
            id_token: string;
        };
        /**
         * MobileTokenResponse
         * @description The JWT pair + user, returned in the BODY (never Set-Cookie) for mobile.
         */
        MobileTokenResponse: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            user: components["schemas"]["UserResponse"];
        };
        /**
         * NotificationPrefs
         * @description Notification preferences for a trip.
         */
        "NotificationPrefs-Input": {
            /**
             * @description What price to compare against threshold
             * @default trip_total
             */
            threshold_type: components["schemas"]["ThresholdType"];
            /**
             * Threshold Value
             * @description Price threshold for notifications
             */
            threshold_value: number | string;
            /**
             * Notify Without Threshold
             * @description Send notification on every refresh regardless of threshold
             * @default false
             */
            notify_without_threshold: boolean;
            /**
             * Email Enabled
             * @description Enable email notifications
             * @default true
             */
            email_enabled: boolean;
            /**
             * Sms Enabled
             * @description Enable SMS notifications
             * @default false
             */
            sms_enabled: boolean;
        };
        /**
         * NotificationPrefs
         * @description Notification preferences for a trip.
         */
        "NotificationPrefs-Output": {
            /**
             * @description What price to compare against threshold
             * @default trip_total
             */
            threshold_type: components["schemas"]["ThresholdType"];
            /**
             * Threshold Value
             * @description Price threshold for notifications
             */
            threshold_value: string;
            /**
             * Notify Without Threshold
             * @description Send notification on every refresh regardless of threshold
             * @default false
             */
            notify_without_threshold: boolean;
            /**
             * Email Enabled
             * @description Enable email notifications
             * @default true
             */
            email_enabled: boolean;
            /**
             * Sms Enabled
             * @description Enable SMS notifications
             * @default false
             */
            sms_enabled: boolean;
        };
        /**
         * PriceSnapshotResponse
         * @description Schema for price snapshot in trip history.
         */
        PriceSnapshotResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Flight Price */
            flight_price?: string | null;
            /** Hotel Price */
            hotel_price?: string | null;
            /** Total Price */
            total_price?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Flight Offers */
            flight_offers?: components["schemas"]["FlightOffer"][];
            /** Hotel Offers */
            hotel_offers?: components["schemas"]["HotelOffer"][];
        };
        /**
         * RefreshStartResponse
         * @description Schema for refresh start response.
         */
        RefreshStartResponse: {
            /** Refresh Group Id */
            refresh_group_id: string;
        };
        /**
         * RefreshStatusResponse
         * @description Schema for refresh status response.
         */
        RefreshStatusResponse: {
            /** Refresh Group Id */
            refresh_group_id: string;
            /** Status */
            status: string;
            /** Total */
            total: number;
            /** Completed */
            completed: number;
            /** Failed */
            failed: number;
            /** In Progress */
            in_progress: number;
            /** Error */
            error?: string | null;
        };
        /**
         * RoomSelectionMode
         * @description Hotel room selection preference modes.
         * @enum {string}
         */
        RoomSelectionMode: "cheapest" | "preferred";
        /**
         * StopsMode
         * @description Flight stops preference modes.
         * @enum {string}
         */
        StopsMode: "nonstop" | "1-stop" | "any";
        /**
         * ThresholdType
         * @description Notification threshold types for price alerts.
         * @enum {string}
         */
        ThresholdType: "trip_total" | "flight_total" | "hotel_total";
        /**
         * TripCreate
         * @description Schema for creating a new trip.
         */
        TripCreate: {
            /**
             * Name
             * @description Trip name (must be unique per user)
             */
            name: string;
            /**
             * Origin Airport
             * @description Origin airport IATA code (e.g., 'SFO')
             */
            origin_airport: string;
            /**
             * Destination Code
             * @description Destination airport IATA code (e.g., 'MCO')
             */
            destination_code: string;
            /**
             * Is Round Trip
             * @description Whether this is a round trip
             * @default true
             */
            is_round_trip: boolean;
            /**
             * Depart Date
             * Format: date
             * @description Departure date
             */
            depart_date: string;
            /**
             * Return Date
             * @description Return date (omit or null for one-way trips)
             */
            return_date?: string | null;
            /**
             * Adults
             * @description Number of adult travelers
             * @default 1
             */
            adults: number;
            /**
             * Track Flights
             * @description Track flight prices for this trip
             * @default true
             */
            track_flights: boolean;
            /**
             * Track Hotels
             * @description Track hotel prices for this trip
             * @default true
             */
            track_hotels: boolean;
            /** @description Flight preferences (optional) */
            flight_prefs?: components["schemas"]["FlightPrefs"] | null;
            /** @description Hotel preferences (required when track_hotels is True) */
            hotel_prefs?: components["schemas"]["HotelPrefs"] | null;
            /** @description Notification settings (required) */
            notification_prefs: components["schemas"]["NotificationPrefs-Input"];
        };
        /**
         * TripDetail
         * @description Schema for detailed trip response with all preferences.
         */
        TripDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Origin Airport */
            origin_airport: string;
            /** Destination Code */
            destination_code: string;
            /**
             * Depart Date
             * Format: date
             */
            depart_date: string;
            /** Return Date */
            return_date?: string | null;
            status: components["schemas"]["TripStatus"];
            /**
             * Track Flights
             * @default true
             */
            track_flights: boolean;
            /**
             * Track Hotels
             * @default true
             */
            track_hotels: boolean;
            /** Current Flight Price */
            current_flight_price?: string | null;
            /** Current Hotel Price */
            current_hotel_price?: string | null;
            /** Total Price */
            total_price?: string | null;
            /** Last Refreshed */
            last_refreshed?: string | null;
            /** Is Round Trip */
            is_round_trip: boolean;
            /** Adults */
            adults: number;
            flight_prefs?: components["schemas"]["FlightPrefs"] | null;
            hotel_prefs?: components["schemas"]["HotelPrefs"] | null;
            notification_prefs?: components["schemas"]["NotificationPrefs-Output"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * TripDetailResponse
         * @description Schema for trip detail response with price history.
         */
        TripDetailResponse: {
            trip: components["schemas"]["TripDetail"];
            /** Price History */
            price_history: components["schemas"]["PriceSnapshotResponse"][];
        };
        /**
         * TripResponse
         * @description Schema for trip list response.
         */
        TripResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Origin Airport */
            origin_airport: string;
            /** Destination Code */
            destination_code: string;
            /**
             * Depart Date
             * Format: date
             */
            depart_date: string;
            /** Return Date */
            return_date?: string | null;
            status: components["schemas"]["TripStatus"];
            /**
             * Track Flights
             * @default true
             */
            track_flights: boolean;
            /**
             * Track Hotels
             * @default true
             */
            track_hotels: boolean;
            /** Current Flight Price */
            current_flight_price?: string | null;
            /** Current Hotel Price */
            current_hotel_price?: string | null;
            /** Total Price */
            total_price?: string | null;
            /** Last Refreshed */
            last_refreshed?: string | null;
        };
        /**
         * TripStatus
         * @description Trip tracking status values.
         * @enum {string}
         */
        TripStatus: "active" | "paused" | "error" | "expired";
        /**
         * TripStatusUpdate
         * @description Schema for updating trip status (pause/resume).
         */
        TripStatusUpdate: {
            /**
             * Status
             * @description New status: 'active' or 'paused'
             * @enum {string}
             */
            status: "active" | "paused";
        };
        /**
         * TripUpdate
         * @description Schema for updating an existing trip. All fields optional.
         */
        TripUpdate: {
            /** Name */
            name?: string | null;
            /** Origin Airport */
            origin_airport?: string | null;
            /** Destination Code */
            destination_code?: string | null;
            /** Is Round Trip */
            is_round_trip?: boolean | null;
            /** Depart Date */
            depart_date?: string | null;
            /** Return Date */
            return_date?: string | null;
            /** Adults */
            adults?: number | null;
            /** Track Flights */
            track_flights?: boolean | null;
            /** Track Hotels */
            track_hotels?: boolean | null;
            flight_prefs?: components["schemas"]["FlightPrefs"] | null;
            hotel_prefs?: components["schemas"]["HotelPrefs"] | null;
            notification_prefs?: components["schemas"]["NotificationPrefs-Input"] | null;
        };
        /**
         * UserResponse
         * @description Response model for authenticated user info.
         */
        UserResponse: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /**
             * Email Notifications Enabled
             * @default true
             */
            email_notifications_enabled: boolean;
            /**
             * Is Admin
             * @default false
             */
            is_admin: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    start_google_auth_v1_auth_google_start_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    google_auth_callback_v1_auth_google_callback_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    mobile_token_v1_auth_mobile_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MobileTokenRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MobileTokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_token_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    logout_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    test_login_v1_auth_test_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    e2e_mint_token_v1_e2e_mint_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MobileTokenResponse"];
                };
            };
        };
    };
    get_current_user_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    list_trips_v1_trips_get: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                status?: components["schemas"]["TripStatus"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_list_TripResponse__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_trip_v1_trips_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_TripDetail_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_all_trips_v1_trips_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_BulkDeleteResponse_"];
                };
            };
        };
    };
    get_trip_details_v1_trips__trip_id__get: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
            };
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_TripDetailResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_trip_v1_trips__trip_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_trip_v1_trips__trip_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_TripDetail_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_all_trips_v1_trips_refresh_all_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_RefreshStartResponse_"];
                };
            };
        };
    };
    refresh_status_v1_trips_refresh_status_get: {
        parameters: {
            query: {
                refresh_group_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_RefreshStatusResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_trip_status_v1_trips__trip_id__status_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripStatusUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_TripResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_trip_v1_trips__trip_id__refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_RefreshStartResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_message_v1_chat_messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_conversations_v1_chat_conversations_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_list_ConversationResponse__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_conversation_v1_chat_conversations__thread_id__get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_ChatResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_conversation_v1_chat_conversations__thread_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_elicitation_v1_chat_elicitation__tool_call_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tool_call_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ElicitationSubmissionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_price_updates_v1_sse_updates_get: {
        parameters: {
            query?: {
                heartbeat_interval?: number;
                poll_interval?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sse_status_v1_sse_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    register_device_token_v1_notifications_device_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceTokenRegister"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceTokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unregister_device_token_v1_notifications_device_token_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceTokenRegister"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_feature_flags_v1_feature_flags_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureFlagsResponse"];
                };
            };
        };
    };
    update_feature_flag_v1_feature_flags__name__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeatureFlagUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureFlagItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
